"use client";
import dynamic from "next/dynamic";
import {useEffect,useMemo,useRef,useState} from "react";
import type {Survey} from "@/lib/supabase/surveys";
import {agroCsv,calculateAgroPlan,cropColor,DEFAULT_AGRO_SETTINGS,EMPTY_ASSIGNMENT,exportAgroGeoJSON,importAgroGeometry,ROW_STATUS_LABELS,validAgroPoint,validateAgroPlan,type AgroPlan,type AgroSettings,type RowAssignment,type RowStatus,type XY} from "@/lib/agro-plan";
import {listAgroPlans,loadAgroPlan,loadAgroPreview,saveAgroPlan,type AgroSaved,type AgroPreview} from "./actions";
const AgroMap=dynamic(()=>import("./agro-map"),{ssr:false,loading:()=> <div className="grid h-[450px] place-items-center rounded-2xl bg-white text-sm">Preparando mapa agrícola…</div>});
type Props={surveys:Survey[];initialSurveyId:string|null;initialPlan:AgroPlan|null;initialName:string;initialSaved:AgroSaved[];initialError:string};
const fmt=(n:number,digits=2)=>n.toLocaleString("pt-BR",{maximumFractionDigits:digits});
const inputClass="mt-1 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";
const button="min-h-11 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold disabled:opacity-40";
const primary="min-h-11 rounded-xl bg-emerald-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40";
const values=(s:AgroSettings)=>({mode:s.mode,spacing:String(s.spacing_m),bearing:String(s.bearing_deg),margin:String(s.end_margin_m),application:s.application_l_ha===null?"":String(s.application_l_ha)});
function settings(v:ReturnType<typeof values>):AgroSettings{return {mode:v.mode,spacing_m:Number(v.spacing),bearing_deg:Number(v.bearing),end_margin_m:Number(v.margin),application_l_ha:v.application.trim()===""?null:Number(v.application)};}
function download(content:string,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function AgroWorkspace({surveys,initialSurveyId,initialPlan,initialName,initialSaved,initialError}:Props){
 const [plan,setPlan]=useState<AgroPlan|null>(initialPlan),[name,setName]=useState(initialName),[surveyId,setSurveyId]=useState(initialSurveyId||"");
 const [params,setParams]=useState(values(initialPlan?.settings||DEFAULT_AGRO_SETTINGS));
 const [drawing,setDrawing]=useState<"boundary"|"exclusion"|null>(null),[draft,setDraft]=useState<XY[]>([]),[selected,setSelected]=useState<string[]>([]),[fit,setFit]=useState(initialPlan?1:0);
 const [center,setCenter]=useState<XY|null>(null),[coordinate,setCoordinate]=useState(""),[message,setMessage]=useState(initialError),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false);
 const [saved,setSaved]=useState(initialSaved),[historyOpen,setHistoryOpen]=useState(false),[assignment,setAssignment]=useState<RowAssignment>({...EMPTY_ASSIGNMENT}),[range,setRange]=useState({from:"1",to:"10"}),[filter,setFilter]=useState(""),[page,setPage]=useState(0);
 const [preview,setPreview]=useState<AgroPreview|null>(null),[previewMessage,setPreviewMessage]=useState(""),[showOrtho,setShowOrtho]=useState(true),[previewBusy,setPreviewBusy]=useState(false);
 const requestId=useRef<string|null>(null),saveLock=useRef(false),previewRequest=useRef(0);
 const fingerprint=JSON.stringify({name,surveyId,plan});
 const latestFingerprint=useRef(fingerprint);useEffect(()=>{latestFingerprint.current=fingerprint;},[fingerprint]);
 const calculated=useMemo(()=>{if(!plan)return {result:null,error:""};try{return {result:calculateAgroPlan(plan),error:""};}catch(e){return {result:null,error:e instanceof Error?e.message:"Plano inválido."};}},[plan]);
 const result=calculated.result;
 const data=useMemo<GeoJSON.FeatureCollection>(()=>plan&&result?exportAgroGeoJSON(name,plan,result):{type:"FeatureCollection",features:[]},[plan,result,name]);
 const rows=result?.rows||[],filtered=rows.filter(r=>`${r.id} ${r.assignment.crop} ${r.assignment.variety} ${ROW_STATUS_LABELS[r.assignment.status]}`.toLocaleLowerCase("pt-BR").includes(filter.toLocaleLowerCase("pt-BR")));
 const visible=filtered.slice(page*40,page*40+40);
 const paramsChanged=!!plan&&JSON.stringify(settings(params))!==JSON.stringify(plan.settings);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 function changed(){setDirty(true);requestId.current=null;}
 function replace(next:AgroPlan){calculateAgroPlan(next);setPlan(next);setSelected([]);setPage(0);changed();}
 function authorizeGeometry(){return !plan||!Object.keys(plan.assignments).length||window.confirm("Regenerar a geometria remove as atribuições de cultura desta versão no editor. As versões salvas permanecem. Continuar?");}
 function begin(mode:"boundary"|"exclusion",edit=false){if(busy)return;setDrawing(mode);setDraft(edit&&plan?[...plan.boundary]:[]);setMessage(mode==="boundary"?"Marque o contorno do talhão. Para editar, arraste os vértices; depois conclua.":"Desenhe uma área que não deve receber linhas, incluindo a margem que você definiu.");}
 function finish(){
  try{
   const next:AgroPlan={schema_version:1,boundary:drawing==="boundary"?draft:plan?.boundary||[],exclusions:drawing==="boundary"?(plan?.exclusions||[]):[...(plan?.exclusions||[]),draft],settings:settings(params),assignments:{}};
   calculateAgroPlan(next);if(!authorizeGeometry())return;replace(next);setDrawing(null);setDraft([]);setFit(n=>n+1);setMessage("Contorno confirmado e linhas geradas. Selecione linhas para definir a cultura.");
  }catch(e){setMessage(e instanceof Error?e.message:"Não foi possível concluir o contorno.");}
 }
 function regenerate(){if(!plan)return;try{const next={...plan,settings:settings(params),assignments:{}};calculateAgroPlan(next);if(!authorizeGeometry())return;replace(next);setMessage("Grade regenerada com os parâmetros informados. Revise os limites e atribua as culturas.");}catch(e){setMessage(e instanceof Error?e.message:"Parâmetros inválidos.");}}
 function removeExclusion(i:number){if(!plan||!window.confirm(`Remover a exclusão ${i+1} desta versão no editor?`)||!authorizeGeometry())return;try{replace({...plan,exclusions:plan.exclusions.filter((_,n)=>i!==n),assignments:{}});setMessage("Exclusão removida do editor. As versões anteriores continuam salvas.");}catch(e){setMessage((e as Error).message);}}
 function selectRow(id:string){setSelected(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]);}
 function apply(){if(!plan||!selected.length)return;try{const next={...plan,assignments:{...plan.assignments}};for(const id of selected)next.assignments[id]={...assignment};const checked=validateAgroPlan(next);calculateAgroPlan(checked);setPlan(checked);changed();setMessage(`Cultura e situação aplicadas a ${selected.length} linha(s). Salve uma versão para consultar no celular e no computador.`);}catch(e){setMessage((e as Error).message);}}
 function selectRange(){const a=Number(range.from),b=Number(range.to);if(!Number.isInteger(a)||!Number.isInteger(b)||a<1||b<a){setMessage("Informe um intervalo válido de números de linha.");return;}const ids=rows.filter(r=>r.number>=a&&r.number<=b).map(r=>r.id);setSelected(ids);setMessage(`${ids.length} linha(s) selecionada(s).`);}
 function go(){const c=coordinate.trim().split(/[,;\s]+/).map(Number),p:XY=[c[1],c[0]];if(c.length!==2||!validAgroPoint(p)){setMessage("Informe latitude, longitude. Exemplo: -21.60, -46.89");return;}setCenter(p);}
 async function importFile(file:File){
  try{
   if(file.size>600000)throw Error("Importe um arquivo de até 600 KB.");const value:unknown=JSON.parse(await file.text());let next:AgroPlan,newName=name;
   if(value&&typeof value==="object"&&"format" in value&&"plan" in value&&value.format==="orion-agro"){
    const source=value as {plan:unknown;name?:unknown};next=validateAgroPlan(source.plan);if(typeof source.name==="string"&&source.name.length<=120)newName=source.name;
   }else{next={schema_version:1,...importAgroGeometry(value),settings:settings(params),assignments:{}};}
   calculateAgroPlan(next);if(dirty&&!window.confirm("Substituir o rascunho no editor? As versões salvas não serão alteradas."))return;
   replace(next);setName(newName);setParams(values(next.settings));setDrawing(null);setDraft([]);setFit(n=>n+1);setMessage("Plano importado e validado. Revise antes de salvar.");
  }catch(e){setMessage(e instanceof Error?e.message:"Arquivo inválido.");}
 }
 async function save(){
  if(!plan||!result||saveLock.current||drawing||paramsChanged)return;saveLock.current=true;setBusy(true);
  try{
   const sentFingerprint=fingerprint;requestId.current ||= crypto.randomUUID();const answer=await saveAgroPlan({id:requestId.current,name,survey_id:surveyId||null,plan});
   if(answer.error||!answer.row)throw Error(answer.error||"Falha ao salvar.");
   setSaved(v=>[answer.row!,...v.filter(p=>p.id!==answer.row!.id)].slice(0,50));setDirty(latestFingerprint.current!==sentFingerprint);setMessage(latestFingerprint.current===sentFingerprint?"Versão salva na sua conta. Abra Planos salvos em outro dispositivo para continuar.":"Versão salva. Existem alterações posteriores no editor: salve outra versão para preservá-las.");
  }catch(e){setMessage((e as Error).message);}finally{setBusy(false);saveLock.current=false;}
 }
 async function openHistory(){setHistoryOpen(true);setBusy(true);try{const data=await listAgroPlans();if(data.error)throw Error(data.error);setSaved(data.rows);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function load(id:string){if(dirty&&!window.confirm("Abrir uma versão salva e substituir o rascunho atual?"))return;setBusy(true);try{const a=await loadAgroPlan(id);if(a.error||!a.row)throw Error(a.error);setPlan(a.row.plan);setParams(values(a.row.plan.settings));setName(a.row.name);setSurveyId(a.row.survey_id||"");setSelected([]);setDrawing(null);setDraft([]);setPage(0);setFit(n=>n+1);setDirty(false);requestId.current=null;setHistoryOpen(false);setPreview(null);setPreviewMessage("");setMessage("Versão carregada. Novas alterações serão salvas como outra versão.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function loadOrtho(){if(!surveyId)return;const seq=++previewRequest.current;setPreviewBusy(true);try{const a=await loadAgroPreview(surveyId);if(seq!==previewRequest.current)return;setPreview(a.preview);setPreviewMessage(a.error||"Ortofoto concluída carregada. O limite do talhão deve ser desenhado por você.");if(a.preview&&!plan)setFit(n=>n+1);}catch{setPreviewMessage("Não foi possível carregar a ortofoto agora.");}finally{if(seq===previewRequest.current)setPreviewBusy(false);}}
 useEffect(()=>{if(!surveyId){setPreview(null);setPreviewMessage("");return;}void loadOrtho();},[surveyId]);
 const filename=(name||"talhao").replace(/[^\w-]/g,"_").slice(0,80);
 return <>
  <div className="mb-4 flex flex-wrap items-center gap-2"><button className={primary} onClick={save} disabled={!plan||!result||busy||!!drawing||paramsChanged}>{busy?"Aguarde…":"Salvar versão na conta"}</button><button className={button} onClick={openHistory} disabled={busy}>Planos salvos</button><span className="text-xs text-slate-500">{dirty?"Rascunho com alterações não salvas":"Versões anteriores são preservadas"}</span></div>
  {message&&<p data-testid="agro-message" role="status" className="mb-4 break-words rounded-xl border border-emerald-200 bg-white p-4 text-sm">{message}</p>}
  {calculated.error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-900">{calculated.error}</p>}
  {historyOpen&&<section className="mb-5 rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><h2 className="font-semibold">Planos salvos · últimas 50 versões</h2><button className={button} onClick={()=>setHistoryOpen(false)}>Fechar</button></div><div className="mt-3 max-h-72 overflow-auto">{saved.length?saved.map(p=><button className="mt-2 flex w-full flex-wrap justify-between gap-2 rounded-xl border p-3 text-left text-sm" key={p.id} disabled={busy} onClick={()=>load(p.id)}><b>{p.name}</b><span>{new Date(p.created_at).toLocaleString("pt-BR")} · abrir versão</span></button>):<p className="py-4 text-sm text-slate-500">Nenhuma versão salva.</p>}</div></section>}
  <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_350px]">
   <section className="min-w-0">
    <div className="mb-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Área do talhão",result?fmt(result.area_m2/10000)+" ha":"—"],["Área útil",result?fmt(result.usable_area_m2/10000)+" ha":"—"],["Linhas / faixas",result?String(rows.length):"—"],["Extensão ativa",result?fmt(result.active_length_m/1000)+" km":"—"]].map(([label,value])=><div key={label} className="min-w-0 rounded-xl border border-white bg-white p-3"><span className="text-xs text-slate-500">{label}</span><strong data-testid={label==="Linhas / faixas"?"agro-row-count":undefined} className="mt-1 block text-xl tabular-nums">{value}</strong></div>)}</div>
    <div className="mb-3 flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>begin("boundary")}>Desenhar talhão</button><button className={button} disabled={!plan||busy} onClick={()=>begin("boundary",true)}>Editar limite</button><button className={button} disabled={!plan||busy} onClick={()=>begin("exclusion")}>Desenhar exclusão</button><button className={button} disabled={!plan&&!preview} onClick={()=>setFit(v=>v+1)}>Enquadrar</button></div>
    {drawing&&<div className="mb-3 flex flex-wrap items-center gap-2 rounded-xl border border-orange-200 bg-orange-50 p-3"><b className="text-xs">{drawing==="boundary"?"Limite do talhão":"Área de exclusão"} · {draft.length} vértices</b><button className={primary} disabled={draft.length<3} onClick={finish}>Concluir contorno</button><button className={button} disabled={!draft.length} onClick={()=>setDraft(v=>v.slice(0,-1))}>Desfazer ponto</button><button className={button} onClick={()=>{setDraft([]);setDrawing(null);}}>Cancelar desenho</button></div>}
    <form onSubmit={e=>{e.preventDefault();go();}} className="mb-3 flex min-w-0 gap-2"><input className={inputClass} aria-label="Latitude e longitude do talhão" placeholder="Latitude, longitude para localizar" value={coordinate} onChange={e=>setCoordinate(e.target.value)}/><button className={button}>Ir</button></form>
    <AgroMap surveyId={surveyId} data={data} draft={draft} drawing={drawing} selected={selected} center={center} fit={fit} preview={preview} showOrtho={showOrtho} onPoint={p=>{if(validAgroPoint(p)&&draft.length<200)setDraft(v=>[...v,p]);}} onMove={(i,p)=>{if(validAgroPoint(p))setDraft(v=>v.map((q,j)=>i===j?p:q));}} onRow={selectRow}/>
    <section className="mt-4 rounded-2xl border border-white bg-white p-4">
     <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Linhas do talhão</h2><span className="text-xs">{selected.length} selecionada(s)</span></div>
     <div className="mt-3 flex flex-wrap gap-2"><button className={button} disabled={!rows.length} onClick={()=>setSelected(rows.map(r=>r.id))}>Selecionar todas</button><button className={button} disabled={!selected.length} onClick={()=>setSelected([])}>Limpar seleção</button></div>
     <div className="mt-3 grid grid-cols-[1fr_1fr_auto] items-end gap-2"><label className="text-xs">Da linha<input className={inputClass} aria-label="Da linha" type="number" min={1} value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/></label><label className="text-xs">Até a linha<input className={inputClass} aria-label="Até a linha" type="number" min={1} value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/></label><button className={button} onClick={selectRange} disabled={!rows.length}>Selecionar</button></div>
     <input className={inputClass} aria-label="Filtrar linhas" placeholder="Buscar linha, cultura ou variedade" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}/>
     <div data-testid="agro-rows" className="mt-3 divide-y divide-slate-100">{visible.map(r=><label key={r.id} className="flex min-h-12 cursor-pointer items-center gap-3 py-2 text-sm"><input type="checkbox" className="h-5 w-5 shrink-0 accent-emerald-800" checked={selected.includes(r.id)} aria-label={`Selecionar ${r.id}`} onChange={()=>selectRow(r.id)}/><span className="h-3 w-3 shrink-0 rounded-full" style={{background:cropColor(r.assignment.crop,r.assignment.status)}}/><b>{r.id}</b><span className="min-w-0 flex-1"><span className="block truncate">{r.assignment.crop||"Sem cultura"}{r.assignment.variety?` · ${r.assignment.variety}`:""}</span><small className="text-slate-500">{ROW_STATUS_LABELS[r.assignment.status]}</small></span><span className="whitespace-nowrap text-xs tabular-nums">{fmt(r.length_m,1)} m</span></label>)}{!rows.length&&<p className="py-5 text-sm text-slate-500">Desenhe ou importe o talhão para gerar as primeiras linhas.</p>}</div>
     {filtered.length>40&&<div className="mt-3 flex items-center justify-between gap-2 text-xs"><button className={button} disabled={page===0} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page+1} / {Math.ceil(filtered.length/40)}</span><button className={button} disabled={(page+1)*40>=filtered.length} onClick={()=>setPage(v=>v+1)}>Próxima</button></div>}
    </section>
   </section>
   <aside className="min-w-0 space-y-4">
    <section className="rounded-2xl bg-white p-4"><h2 className="mb-3 font-semibold">01 · Talhão e levantamento</h2><label className="block text-xs">Nome do talhão<input aria-label="Nome do talhão" maxLength={120} className={inputClass} value={name} onChange={e=>{setName(e.target.value);changed();}}/></label><label className="mt-3 block text-xs">Vincular ao levantamento<select aria-label="Levantamento do plano agro" className={inputClass} value={surveyId} onChange={e=>{setSurveyId(e.target.value);changed();previewRequest.current++;setPreviewBusy(false);setPreview(null);setPreviewMessage("");}}><option value="">Planejamento independente</option>{surveys.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className={button+" mt-3 w-full"} disabled={!surveyId||previewBusy} onClick={loadOrtho}>{previewBusy?"Carregando…":"Carregar ortofoto concluída"}</button>{preview&&<label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={showOrtho} onChange={e=>setShowOrtho(e.target.checked)}/>Mostrar ortofoto</label>}{previewMessage&&<p className="mt-2 text-xs leading-5 text-slate-500">{previewMessage}</p>}
    </section>
    <section className="rounded-2xl bg-white p-4"><h2 className="mb-3 font-semibold">02 · Gerar linhas / faixas</h2><div className="grid grid-cols-2 gap-2" role="group" aria-label="Tipo de planejamento">{([['planting','Plantio'],['spraying','Pulverização']] as const).map(([v,label])=><button key={v} className={params.mode===v?primary:button} aria-pressed={params.mode===v} onClick={()=>setParams(p=>({...p,mode:v}))}>{label}</button>)}</div>
     <label className="mt-3 block text-xs">{params.mode==="planting"?"Espaçamento entre linhas (m)":"Distância entre faixas centrais (m)"}<input aria-label="Espaçamento em metros" type="number" min={0.2} max={100} step="any" className={inputClass} value={params.spacing} onChange={e=>setParams(p=>({...p,spacing:e.target.value}))}/></label>
     <label className="mt-3 block text-xs">Rumo da grade (0° = norte UTM)<input aria-label="Rumo da grade" type="number" min={0} max={359.99} step="any" className={inputClass} value={params.bearing} onChange={e=>setParams(p=>({...p,bearing:e.target.value}))}/></label>
     <label className="mt-3 block text-xs">Recuo nas pontas de cada segmento (m)<input aria-label="Recuo nas pontas" type="number" min={0} max={100} step="any" className={inputClass} value={params.margin} onChange={e=>setParams(p=>({...p,margin:e.target.value}))}/></label>
     {params.mode==="spraying"&&<label className="mt-3 block text-xs">Volume de aplicação informado (L/ha), opcional<input aria-label="Volume informado por hectare" type="number" min={0.01} step="any" className={inputClass} placeholder="Sem recomendação automática" value={params.application} onChange={e=>setParams(p=>({...p,application:e.target.value}))}/></label>}
     <button className={primary+" mt-4 w-full"} onClick={regenerate} disabled={!plan||!!drawing||busy}>Gerar linhas com estes parâmetros</button>
     {paramsChanged&&<p role="status" className="mt-2 text-xs text-amber-800">Parâmetros editados: gere novamente antes de salvar/exportar.</p>}
     <p className="mt-3 text-xs leading-5 text-slate-500">Valores iniciais são exemplos editáveis, não recomendações agronômicas. Linhas retas em planta; não são linhas em nível.</p>
     {plan?.exclusions.length? <div className="mt-3 border-t pt-3 text-xs"><b>{plan.exclusions.length} exclusão(ões)</b>{plan.exclusions.map((_,i)=><button key={i} className="mt-2 block text-red-800 underline" disabled={!!drawing} onClick={()=>removeExclusion(i)}>Remover exclusão {i+1}</button>)}</div>:null}
    </section>
    <section id="agro-culture-panel" className="scroll-mt-4 rounded-2xl border border-emerald-200 bg-white p-4"><h2 className="font-semibold">03 · O que vai em cada linha</h2><p className="mt-1 text-xs text-slate-500">Selecione no mapa ou na lista e aplique.</p>
     <label className="mt-3 block text-xs">Cultura<input aria-label="Cultura das linhas" list="agro-crops" maxLength={80} className={inputClass} placeholder="Café, soja, milho…" value={assignment.crop} onChange={e=>setAssignment(a=>({...a,crop:e.target.value}))}/></label><datalist id="agro-crops">{['Café','Soja','Milho','Cana','Citrus','Eucalipto','Outra'].map(v=><option key={v} value={v}/>)}</datalist>
     <label className="mt-3 block text-xs">Variedade<input aria-label="Variedade das linhas" maxLength={100} className={inputClass} value={assignment.variety} onChange={e=>setAssignment(a=>({...a,variety:e.target.value}))}/></label>
     <label className="mt-3 block text-xs">Situação<select aria-label="Situação das linhas" className={inputClass} value={assignment.status} onChange={e=>setAssignment(a=>({...a,status:e.target.value as RowStatus}))}>{Object.entries(ROW_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
     <label className="mt-3 block text-xs">Observação<textarea aria-label="Observação das linhas" maxLength={300} className={inputClass} rows={2} value={assignment.notes} onChange={e=>setAssignment(a=>({...a,notes:e.target.value}))}/></label>
     <button className={primary+" mt-3 w-full"} disabled={!selected.length||!plan||busy||!!drawing||paramsChanged} onClick={apply}>Aplicar às {selected.length} selecionadas</button>
    </section>
    <section className="rounded-2xl bg-white p-4"><h2 className="mb-3 font-semibold">04 · Importar e exportar</h2><label className="block text-xs">GeoJSON de talhão ou JSON Orion<input aria-label="Importar plano agro" type="file" accept=".json,.geojson" className="mt-2 w-full min-w-0 text-xs" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value="";}}/></label>
     <div className="mt-3 grid gap-2"><button className={button} disabled={!plan||!result||paramsChanged||!!drawing} onClick={()=>{if(plan)download(JSON.stringify({format:"orion-agro",name,plan},null,2),"application/json",filename+'-editavel.json');}}>Exportar JSON editável</button><button className={button} disabled={!plan||!result||paramsChanged||!!drawing} onClick={()=>download(JSON.stringify(data,null,2),"application/geo+json",filename+'.geojson')}>Exportar GeoJSON</button><button className={button} disabled={!result||paramsChanged||!!drawing} onClick={()=>{if(result)download(agroCsv(result),"text/csv;charset=utf-8",filename+'-linhas.csv');}}>Exportar CSV das linhas</button></div>
     <p className="mt-3 text-xs leading-5 text-slate-500">Arquivos para planejamento e GIS. Não enviam comandos ao drone.</p>
    </section>
   </aside>
  </div>
  {selected.length>0&&<div className="fixed bottom-3 left-3 right-3 z-30 flex items-center justify-between gap-2 rounded-2xl bg-emerald-950 p-3 text-sm text-white shadow-xl xl:hidden"><b>{selected.length} linha(s) selecionada(s)</b><button type="button" className="rounded-xl bg-white px-3 py-2 font-semibold text-emerald-950" onClick={()=>document.getElementById("agro-culture-panel")?.scrollIntoView({behavior:"smooth",block:"start"})}>Definir cultura</button></div>}
  <section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-6 text-amber-950"><h2 className="font-bold">Escopo desta simulação</h2><p>Geometrias em WGS84; cálculos de área e comprimento em {result?.epsg||"UTM da área"}. Não mede precisão topográfica nem define o limite legal da propriedade. Não considera relevo, vento, deriva, manobras, autonomia ou obstáculos não desenhados. Recortes atingem linhas centrais, não uma faixa molhada. O recuo nas pontas não é uma margem de segurança geral.</p>{result?.application_l!==null&&result?.application_l!==undefined&&<p className="mt-2 font-semibold">Volume teórico informado para toda a área útil: {fmt(result.application_l)} L. Não é dose de produto, cobertura comprovada ou recomendação de aplicação.</p>}<p>Sem pilotagem automática, prescrição agronômica ou integração com o controle de pulverização nesta versão.</p></section>
 </>;
}
