import type {TerrainSample,SlopeAreaSummary,TerrainPoint} from "@/lib/terrain-analysis";
export type SlopeSnapshot={
  source:{resultId:string;jobId:string;surveyId:string;createdAt:string;crs:string|null;resolutionM:number[]|null};
  name:string;generatedAt:string;marks:(TerrainSample&{id:number})[];
  area:{summary:SlopeAreaSummary;computedAt:string;polygon:TerrainPoint[]}|null;
};
const notice="Estimativa do DTM, não precisão certificada. Inclinação local de maior declive por Horn 3×3, sem interpolar áreas sem dados. Não valida segurança de máquinas nem aptidão agronômica. Áreas por centro de célula são aproximadas e horizontais; não são áreas de superfície.";
export function slopeAnalysisGeoJSON(value:SlopeSnapshot){
  const features:GeoJSON.Feature[]=value.marks.map(p=>({type:"Feature",properties:{name:`P${p.id}`,slope_pct:p.slopePct,elevation_m:p.elevationM,status:p.status,requested_position:p.position,dtm_column:p.column,dtm_row:p.row,estimated:true},geometry:{type:"Point",coordinates:p.cellCenter||p.position}}));
  if(value.area)features.push({type:"Feature",properties:{name:value.name,analysis:value.area.summary,computed_at:value.area.computedAt,estimated:true},geometry:{type:"Polygon",coordinates:[[...value.area.polygon,value.area.polygon[0]]]}});
  return {type:"FeatureCollection",schema_version:1,name:value.name,source:value.source,generated_at:value.generatedAt,notice,features};
}
const esc=(v:unknown)=>String(v??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const n=(v:number|null,d=1)=>v===null?"—":v.toLocaleString("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d});
export function slopeReportHtml(value:SlopeSnapshot):string {
  const s=value.area?.summary;
  const stats=s?`<section><h2>Área desenhada</h2><div class="metrics"><div>Média válida<strong>${n(s.meanPct)}%</strong></div><div>Mínima<strong>${n(s.minPct)}%</strong></div><div>Máxima local<strong>${n(s.maxPct)}%</strong></div></div><p>Área do polígono no CRS projetado: ${n(s.polygonAreaM2/10000,4)} ha · Cobertura válida estimada: ${n(s.coveragePct)}%.</p><p>Área válida: ${n(s.validAreaM2/10000,4)} ha · Sem dados ou fora da cobertura: aproximadamente ${n(s.unavailableAreaM2/10000,4)} ha.</p>${s.maxPct!==null&&s.maxPct>100?"<p class=warning>O DTM contém inclinações locais acima de 100%. Revise transições abruptas e a qualidade do modelo; esse extremo não é a média do talhão.</p>":""}${!s.validCells?"<p class=warning>Não há células válidas. Não equivale a terreno plano.</p>":""}<table><thead><tr><th>Faixa</th><th>Área estimada</th><th>% da parte válida</th></tr></thead><tbody>${s.classes.map(c=>`<tr><td><i style="background:${c.color}"></i>${esc(c.label)}</td><td>${n(c.areaM2/10000,4)} ha</td><td>${n(c.validSharePct)}%</td></tr>`).join("")}</tbody></table><p class="muted">${s.validCells.toLocaleString("pt-BR")} células válidas. Método: ${esc(s.method)}. Valores sem dados não entram na média ou nos extremos. Faixas com limites coincidentes incluem o limite superior na classe inferior. As áreas de borda são aproximadas.</p></section>`:"";
  const points=value.marks.length?`<section><h2>Pontos marcados</h2><table><thead><tr><th>Ponto</th><th>Inclinação</th><th>Elevação</th><th>Latitude / longitude da célula</th></tr></thead><tbody>${value.marks.map(p=>`<tr><td>P${p.id}</td><td>${n(p.slopePct)}%</td><td>${n(p.elevationM,2)} m</td><td>${n((p.cellCenter||p.position)[1],6)}, ${n((p.cellCenter||p.position)[0],6)}</td></tr>`).join("")}</tbody></table></section>`:"";
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orion Maps — Inclinação da seleção</title><style>
  *{box-sizing:border-box}body{font:14px/1.5 Arial,sans-serif;color:#163b30;max-width:850px;margin:28px auto;padding:0 24px}header{border-bottom:3px solid #205b40;padding-bottom:18px}.eyebrow{font-size:11px;letter-spacing:2px}h1{font-size:26px;line-height:1.25;margin:8px 0}h2{font-size:18px;margin:20px 0 10px}button{border:0;border-radius:9px;padding:12px 18px;background:#174f39;color:white;cursor:pointer}.muted{font-size:11px;color:#526b61;overflow-wrap:anywhere}.metrics{display:flex;gap:10px}.metrics>div{background:#f0f5eb;flex:1;padding:12px;border-radius:9px}.metrics strong{display:block;font-size:24px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px 6px;text-align:left;border-bottom:1px solid #dbe5da}th{background:#f2f6ef}i{display:inline-block;width:10px;height:10px;margin-right:7px}.warning{background:#fff6df;border:1px solid #e9cb81;padding:12px;font-size:12px}section{margin:18px 0}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4;margin:16mm}@media print{body{margin:0;max-width:none;padding:0}button{display:none}.metrics>div,th,i{-webkit-print-color-adjust:exact;print-color-adjust:exact}h2{break-after:avoid}}
  </style></head><body><button type="button" id="print-report">Imprimir / Salvar em PDF</button><header><p class="eyebrow">ORION MAPS DRONES · ANÁLISE DA SELEÇÃO</p><h1>Inclinação do terreno</h1><p>${esc(value.name)}</p><p class="muted">Gerado em ${esc(new Date(value.generatedAt).toLocaleString("pt-BR"))}. Esta é uma análise da seleção, não o relatório completo do levantamento.</p></header>${stats}${points}<section class="warning">${esc(notice)}</section><footer class="muted"><p>Fonte: DTM ${esc(value.source.crs)} · grade ${value.source.resolutionM?.map(x=>n(x,2)).join(" × ")||"—"} m.</p><p>Levantamento: ${esc(value.source.surveyId)}<br>Processamento: ${esc(value.source.jobId)}<br>Resultado DTM: ${esc(value.source.resultId)}<br>Resultado registrado em: ${esc(value.source.createdAt)}</p><p>Nenhuma foto, arquivo de terreno ou processamento foi alterado por esta consulta. Coordenadas e casas decimais não indicam a precisão do levantamento.</p></footer></body></html>`;
}
