import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAccessToken, getCurrentUser } from "@/lib/supabase/auth";
import { listImages, listSurveys, type Survey, type SurveyImage } from "@/lib/supabase/surveys";
import { signOutAction } from "./actions";
import { ImageWorkspace, SurveyForm, SurveySearch } from "./workspace";

export default async function PainelPage({ searchParams }: { searchParams: Promise<{ levantamento?: string; novo?: string }> }) {
  const [user, token, query] = await Promise.all([getCurrentUser(), getCurrentAccessToken(), searchParams]);
  if (!user || !token) redirect("/entrar");
  let surveys: Survey[] = [], images: SurveyImage[] = [], error = "", imageError = "";
  try { surveys = await listSurveys(token); } catch { error = "Não foi possível carregar os levantamentos. Atualize a página em instantes."; }
  const active = surveys.find(survey => survey.id === query.levantamento);
  if (active) { try { images = await listImages(active.id, user.id, token); } catch { imageError = "Não foi possível consultar as fotos. Atualize a página antes de enviar arquivos."; } }
  return <main className="mx-auto min-h-screen max-w-[1500px] px-5 py-7 sm:px-9">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-emerald-950/10 pb-6 print:hidden"><Link href="/painel" className="text-xl font-bold tracking-tight">ORION <span className="font-normal">MAPS</span></Link><div className="flex items-center gap-4"><span className="hidden text-sm text-slate-500 sm:block">{user.email}</span><form action={signOutAction}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">Sair</button></form></div></header>
    <section className="flex flex-wrap items-end justify-between gap-4 py-9 print:hidden"><div><p className="text-xs font-bold tracking-[0.2em] text-emerald-700">SEU ESPAÇO DE TRABALHO</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Do levantamento ao mapa.</h1><p className="mt-3 text-sm text-slate-600">Organize seus voos e reúna as imagens de cada área.</p></div><Link href="/painel?novo=1" className="rounded-xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white">+ Novo levantamento</Link></section>
    {error ? <p role="alert" className="rounded-xl bg-red-50 p-5 text-red-800">{error}</p> : <div className="grid gap-7 lg:grid-cols-[290px_minmax(0,1fr)]">
      <aside className="print:hidden"><div className="flex items-center justify-between"><h2 className="font-semibold">Levantamentos</h2><span className="rounded-full bg-white px-3 py-1 text-xs">{surveys.length}</span></div><SurveySearch surveys={surveys} activeId={active?.id} /><div className="mt-7 rounded-2xl bg-emerald-950 p-5 text-emerald-50"><p className="text-xs uppercase tracking-widest text-emerald-300">Próxima etapa</p><h3 className="mt-2 font-semibold">Motor de fotogrametria</h3><p className="mt-2 text-sm leading-6 text-emerald-100/80">Servidor não conectado. As fotos ficam organizadas aqui até configurarmos o processamento.</p></div></aside>
      <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8">
        {query.novo === "1" ? <><p className="text-xs font-semibold uppercase tracking-widest text-emerald-700">Novo levantamento</p><h2 className="mb-7 mt-2 text-2xl font-semibold">Dê um nome à sua próxima área.</h2><SurveyForm /></> : active ? <><div className="mb-7 border-b border-slate-100 pb-6"><p className="text-xs font-semibold uppercase tracking-widest text-emerald-700">Levantamento pessoal</p><h2 className="mt-2 break-words text-3xl font-semibold">{active.name}</h2><p className="mt-3 text-sm text-slate-500">{active.location || "Local a definir"} · {active.drone || "Drone a definir"} · {active.flight_date?.split("-").reverse().join("/") || "Data a definir"}</p>{active.notes && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{active.notes}</p>}</div><details className="mb-6 rounded-xl border border-slate-200 p-4 print:hidden"><summary className="cursor-pointer text-sm font-semibold">Editar informações do levantamento</summary><div className="pt-5"><SurveyForm key={active.id} survey={active} /></div></details>{imageError ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{imageError}</p> : <ImageWorkspace key={active.id} survey={active} images={images} />}<div className="mt-8 rounded-xl bg-slate-50 p-5"><h3 className="font-semibold">Resultados do processamento</h3><p className="mt-2 text-sm leading-6 text-slate-500">Ortomosaico, modelos de elevação e nuvem de pontos aparecerão aqui quando o motor de processamento estiver conectado. Nenhum processamento foi iniciado.</p></div></> : <div className="flex min-h-96 flex-col items-center justify-center text-center"><span className="rounded-2xl bg-emerald-50 px-5 py-4 text-3xl text-emerald-800">↗</span><h2 className="mt-5 text-2xl font-semibold">{query.levantamento ? "Levantamento não encontrado" : "Seu trabalho, organizado por área"}</h2><p className="mt-3 max-w-md text-sm leading-7 text-slate-500">Crie um levantamento para registrar o voo, enviar as fotos originais e preparar seus dados para o processamento.</p><Link href="/painel?novo=1" className="mt-6 rounded-xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white">Criar levantamento</Link></div>}
      </section>
    </div>}
    <footer className="py-8 text-center text-xs text-slate-400">Orion Maps · Ambiente pessoal de levantamentos</footer>
  </main>;
}
