"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import Image from "next/image";
import {useMemo,useState} from "react";
import {unzipSync,strFromU8} from "fflate";
import {generateGrid,parseBoundaryGeoJson,type Coordinate} from "@/lib/flight-plan";
import {droneProfiles,findCamera,type CameraProfile} from "@/lib/drone-cameras";
import {calculateGsd} from "@/lib/gsd";
import {missionCsv,previewKmz} from "@/lib/mission-export";
import "./waypoints.css";
const PlanningCanvas=dynamic(()=>import("./planning-canvas"),{ssr:false,loading:()=> <div className="mission-map loading-map">Preparando editor…</div>});
type Mode="manual"|"grid"|"double";
type Settings={diagonalFov?:number;height:number;speed:number;gimbal:number;bearing:number;front:number;side:number;sensorWidth:number;sensorHeight:number;focal:number;imageWidth:number;imageHeight:number};
type Plan={version:1;name:string;mode:Mode;points:Coordinate[];settings:Settings;drone:string;cameraId?:string};
const defaults:Settings={height:100,speed:5,gimbal:-90,bearing:0,front:80,side:70,sensorWidth:13.2,sensorHeight:8.8,focal:8.8,imageWidth:5472,imageHeight:3648};
const number=(n:number,digits=1)=>n.toLocaleString("pt-BR",{maximumFractionDigits:digits});
const distance=(a:Coordinate,b:Coordinate)=>{const k=Math.PI/180;return Math.hypot((b[0]-a[0])*k*Math.cos((a[1]+b[1])/2*k),(b[1]-a[1])*k)*6371008.8;};
const storageKey="orion-missions-v1";
function validPoint(p:unknown):p is Coordinate{return Array.isArray(p)&&p.length===2&&p.every(n=>typeof n==="number"&&Number.isFinite(n))&&Math.abs(p[0])<=180&&Math.abs(p[1])<=75;}
function validatePlan(value:unknown):Plan{const p=value as Plan;if(!p||p.version!==1||typeof p.name!=="string"||p.name.length>120||!["manual","grid","double"].includes(p.mode)||!Array.isArray(p.points)||p.points.length>200||!p.points.every(validPoint)||!p.settings||Object.keys(defaults).some(key=>!Number.isFinite(p.settings[key as keyof Settings]))||typeof p.drone!=="string"||p.drone.length>100)throw new Error("Plano Orion inválido ou de versão não suportada.");if(p.settings.diagonalFov!==undefined&&(!Number.isFinite(p.settings.diagonalFov)||p.settings.diagonalFov<=0||p.settings.diagonalFov>=180))throw new Error("Campo de visão inválido.");if(p.cameraId!==undefined&&(typeof p.cameraId!=="string"||p.cameraId.length>100))throw new Error("Câmera inválida.");return p;}
function download(content:BlobPart,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export default function WaypointsPage(){
 const [name,setName]=useState("Meu primeiro voo"),[mode,setMode]=useState<Mode>("manual"),[points,setPoints]=useState<Coordinate[]>([]),[settings,setSettings]=useState(defaults),[drone,setDrone]=useState("");
 const [history,setHistory]=useState<Coordinate[][]>([]),[drawing,setDrawing]=useState(true),[center,setCenter]=useState<Coordinate|null>(null),[fit,setFit]=useState(0),[coordinate,setCoordinate]=useState(""),[message,setMessage]=useState(""),[saved,setSaved]=useState<Plan[]|null>(null);
 const [cameraId,setCameraId]=useState("");
 const selectedDrone=droneProfiles.find(p=>p.name===drone);
 const candidateCamera=findCamera(drone,cameraId);
 const selectedCamera=candidateCamera&&candidateCamera.fov===settings.diagonalFov&&candidateCamera.imageWidth===settings.imageWidth&&candidateCamera.imageHeight===settings.imageHeight?candidateCamera:undefined;
 function applyCamera(camera:CameraProfile){setCameraId(camera.id);setSettings(s=>({...s,diagonalFov:camera.fov,imageWidth:camera.imageWidth,imageHeight:camera.imageHeight}));}
 function customCamera(){setCameraId("");setSettings(s=>{const next={...s};delete next.diagonalFov;return next;});}
 const [locating,setLocating]=useState(false);
 const [adjustingPosition,setAdjustingPosition]=useState(false);
 const [userPosition,setUserPosition]=useState<{point:Coordinate;accuracy:number;source?:"manual"}|null>(null);
 function adjustPosition(p:Coordinate){if(!validPoint(p))return;setUserPosition({point:p,accuracy:0,source:"manual"});setCoordinate(`${p[1].toFixed(6)}, ${p[0].toFixed(6)}`);setAdjustingPosition(false);setMessage("Posição informada por você. Nenhum waypoint foi criado. Esta posição não é uma medição GPS.");}
 function locateMe(){
  if(locating)return;
  if(!window.isSecureContext||!navigator.geolocation){setMessage("Este navegador não disponibilizou a localização. Use latitude e longitude no campo acima.");return;}
  setAdjustingPosition(false);setLocating(true);setMessage("Permita o acesso à localização quando o navegador solicitar.");
  navigator.geolocation.getCurrentPosition(position=>{
   setLocating(false);
   const p:Coordinate=[position.coords.longitude,position.coords.latitude];
   if(!validPoint(p)){setMessage("A localização recebida está fora da área suportada pelo planejador. Use latitude e longitude.");return;}
   setUserPosition({point:p,accuracy:position.coords.accuracy});
   setCoordinate(`${p[1].toFixed(6)}, ${p[0].toFixed(6)}`);
   setCenter(p);
   setMessage(`Localização aproximada do navegador. Latitude ${p[1].toFixed(6)}, longitude ${p[0].toFixed(6)}. Precisão aproximada: ${number(position.coords.accuracy,0)} m. Confira a posição antes de planejar.`);
  },error=>{
   setLocating(false);
   setMessage(error.code===1?"Acesso à localização bloqueado. Nas permissões deste site no navegador, permita Localização e tente novamente. Você também pode informar latitude e longitude.":error.code===3?"A localização demorou para responder. Tente novamente ou informe latitude e longitude.":"Não foi possível obter sua localização. Confira a localização do dispositivo e tente novamente, ou informe latitude e longitude.");
  },{enableHighAccuracy:true,timeout:15000,maximumAge:30000});
 }
 function changePoints(next:Coordinate[]){setHistory(h=>[...h.slice(-49),points]);setPoints(next);setMessage("");}
 const calculation=useMemo(()=>{try{
  if(settings.height<=0||settings.height>500||settings.speed<=0||settings.speed>30||settings.gimbal< -90||settings.gimbal>0||!Object.values(settings).every(Number.isFinite))throw new Error("Revise altura (1–500 m), velocidade (0–30 m/s) e gimbal (−90 a 0°).");
  if(points.some(p=>distance(points[0],p)>20000))throw new Error("Divida o plano em áreas de até 20 km.");
  const gsd=calculateGsd({diagonalFov:settings.diagonalFov,sensorWidth:settings.sensorWidth,sensorHeight:settings.sensorHeight,focalLength:settings.focal,imageWidth:settings.imageWidth,imageHeight:settings.imageHeight,height:settings.height,frontOverlap:settings.front,sideOverlap:settings.side,speed:settings.speed,targetGsd:3});
  if(mode==="manual"){const length=points.slice(1).reduce((s,p,i)=>s+distance(points[i],p),0);return {gsd,legs:points.length>=2?[points]:[],photos:[] as Coordinate[],area:0,length,seconds:length/settings.speed,error:""};}
  if(points.length<3)return {gsd,legs:[],photos:[],area:0,length:0,seconds:0,error:""};
  if(settings.gimbal!==-90)throw new Error("A grade desta versão considera câmera para baixo (gimbal −90°). O voo oblíquo terá um modo separado.");
  return {...generateGrid(points,{spacing:gsd.lineSpacing,photoSpacing:gsd.photoSpacing,bearing:settings.bearing,speed:settings.speed,doubleGrid:mode==="double"}),gsd,error:""};
 }catch(e){return {legs:[],photos:[],area:0,length:0,seconds:0,error:e instanceof Error?e.message:"Revise os parâmetros.",gsd:undefined};}},[points,settings,mode]);
 const plan:Plan={version:1,name,mode,points,settings,drone,cameraId};
 function setField(key:keyof Settings,value:string){if(["sensorWidth","sensorHeight","focal","imageWidth","imageHeight","diagonalFov"].includes(key))setCameraId("");setSettings(s=>({...s,[key]:value===""?NaN:Number(value)}));}
 function load(p:Plan){changePoints(p.points);setName(p.name);setMode(p.mode);setSettings(p.settings);setDrone(p.drone);setCameraId(p.cameraId||"");setFit(n=>n+1);setDrawing(false);setSaved(null);setMessage("Plano carregado. Confira os parâmetros antes de exportar.");}
 function save(){try{validatePlan(plan);if(calculation.error)throw new Error();const plans:Plan[]=JSON.parse(localStorage.getItem(storageKey)||"[]");localStorage.setItem(storageKey,JSON.stringify([plan,...plans.filter(p=>p.name!==name)].slice(0,30)));setMessage("Plano salvo neste navegador. Exporte o JSON para guardar uma cópia.");}catch{setMessage("Não foi possível salvar. Confira os parâmetros ou exporte uma cópia JSON.");}}
 function openSaved(){try{const value:unknown=JSON.parse(localStorage.getItem(storageKey)||"[]");if(!Array.isArray(value))throw new Error();setSaved(value.map(validatePlan));}catch{setMessage("Não foi possível ler os planos deste navegador.");}}
 function locate(){const p=coordinate.trim().split(/[;,\s]+/).map(Number);if(p.length!==2||!validPoint([p[1],p[0]])){setMessage("Informe latitude e longitude. Ex.: -23.55, -46.63");return;}setCenter([p[1],p[0]]);setMessage("");}
 async function importFile(file:File){try{
  if(file.size>2*1024*1024)throw new Error("Importe um arquivo de até 2 MB.");let text:string;
  if(file.name.toLowerCase().endsWith(".kmz")){const entries=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:f=>f.name.toLowerCase().endsWith(".kml")&&f.originalSize<=2*1024*1024});const kml=Object.values(entries);if(kml.length!==1)throw new Error("O KMZ deve conter um único KML de até 2 MB.");text=strFromU8(kml[0]);}else text=await file.text();
  if(text.trim().startsWith("<")){const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("KML inválido.");const polygons=doc.getElementsByTagNameNS("*","Polygon");if(polygons.length!==1||doc.getElementsByTagNameNS("*","innerBoundaryIs").length)throw new Error("Importe um KML com um único polígono sem recortes internos.");const coords=polygons[0].getElementsByTagNameNS("*","coordinates")[0]?.textContent?.trim();if(!coords)throw new Error("Coordenadas não encontradas.");changePoints(parseBoundaryGeoJson({type:"Polygon",coordinates:[coords.split(/\s+/).map(t=>t.split(",").slice(0,2).map(Number))]}));setMode("grid");}
  else{const json=JSON.parse(text);if(json.version===1){load(validatePlan(json));return;}changePoints(parseBoundaryGeoJson(json));setMode("grid");}setFit(n=>n+1);setDrawing(false);setMessage("Área importada. Confira câmera, altura e sobreposição.");
 }catch(e){setMessage(e instanceof Error?e.message:"Não foi possível importar este arquivo.");}}
 const filename=name.replace(/[^a-zA-Z0-9_-]/g,"_").slice(0,80)||"orion-voo";
 const sliderFields:[keyof Settings,string,string,number,number][]=[["height","Altura planejada","m",1,500],["speed","Velocidade","m/s",0.1,30],["gimbal","Gimbal","°",-90,0]];
 if(mode!=="manual")sliderFields.push(["front","Sobreposição frontal","%",0,99],["side","Sobreposição lateral","%",0,99],["bearing","Rumo da grade","°",0,359]);
 return <div className="flight-app"><aside className="flight-sidebar"><Link className="flight-brand" href="/painel"><Image src="/orion-drone-concept.png" width={48} height={48} className="brand-image" alt="Símbolo de drone Orion"/><span>ORION<small>MAPS / FIELD SYSTEMS</small></span></Link><div className="sidebar-label">ÁREA DE TRABALHO</div><nav><Link href="/waypoints" aria-current="page"><span>01</span>Waypoint KMZ</Link><Link href="/gsd"><span>02</span>Calculadora GSD</Link><Link href="/painel"><span>03</span>Levantamentos</Link><Link href="/processamento"><span>04</span>Processamento</Link></nav><div className="sidebar-bottom"><span className="status-dot"/>PLANEJAMENTO LOCAL<small>Os planos ficam neste navegador até você exportar.</small></div></aside>
 <main className="flight-main"><header className="flight-topbar"><span>MISSÕES / WAYPOINT KMZ</span><Link href="/painel">Voltar ao painel ↗</Link></header><section className="mission-title"><div><div className="eyebrow">DO TERRENO AO TRAJETO</div><h1>Planeje cada passagem.</h1><p>Waypoints e grades de levantamento. Um plano claro, ponto a ponto.</p></div><div className="title-actions"><button onClick={openSaved} className="flight-button">Meus planos</button><button onClick={save} className="flight-button primary">Salvar plano ↗</button></div></section>
 <div className="mission-metrics">{[["PONTOS",mode==="manual"?points.length:calculation.legs.length*2,""],["DISTÂNCIA",number(calculation.length/1000),"km"],["TEMPO EM FAIXAS",number(calculation.seconds/60),"min"],["FOTOS ESTIMADAS",mode==="manual"?"—":calculation.photos.length,""],["ÁREA",calculation.area?number(calculation.area/10000,2):"—","ha"],["ALTURA",Number.isFinite(settings.height)?settings.height:"—","m"]].map(([label,value,unit])=><div key={label}><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>)}</div>
 {message&&<div role="status" className="flight-message">{message}<button aria-label="Fechar aviso" onClick={()=>setMessage("")}>×</button></div>}
 {saved!==null&&<section className="saved-plans"><div><h2>Meus planos · neste navegador</h2><button onClick={()=>setSaved(null)}>Fechar</button></div>{saved.length?saved.map((p,i)=><button key={i} onClick={()=>load(p)}>{p.name}<small>{p.points.length} pontos · {p.mode}</small><span>Abrir ↗</span></button>):<p>Nenhum plano salvo. Salve um plano ou importe um JSON Orion.</p>}</section>}
 <div className="mission-layout"><section className="map-workspace"><form className="map-search" onSubmit={e=>{e.preventDefault();locate();}}><span>⌖</span><input aria-label="Ir para latitude e longitude" placeholder="Latitude, longitude · ex.: -23.55, -46.63" value={coordinate} onChange={e=>setCoordinate(e.target.value)}/><button>Ir às coordenadas</button></form><div className="map-toolbar"><button type="button" className="location-button" onClick={locateMe} disabled={locating} aria-busy={locating}>{locating?"Localizando…":"⌖ Minha localização"}</button><button type="button" className={adjustingPosition?"selected":""} aria-pressed={adjustingPosition} disabled={locating} onClick={()=>{setAdjustingPosition(!adjustingPosition);setMessage(adjustingPosition?"Ajuste cancelado. Sua posição anterior foi mantida.":"Clique no mapa para indicar sua posição. Esse clique não cria um waypoint. Use Cancelar ajuste para desistir.");}}>{adjustingPosition?"Cancelar ajuste":"Ajustar minha posição"}</button><button disabled={adjustingPosition} className={drawing?"selected":""} onClick={()=>setDrawing(!drawing)}>{drawing?"● Adicionando pontos":"Adicionar pontos"}</button><button disabled={!history.length} onClick={()=>{setPoints(history.at(-1)!);setHistory(h=>h.slice(0,-1));}}>Desfazer</button><button disabled={!points.length} onClick={()=>changePoints([])}>Limpar</button><button disabled={!points.length} onClick={()=>setFit(n=>n+1)}>Enquadrar</button></div>
 <PlanningCanvas adjustingPosition={adjustingPosition} onPositionPick={adjustPosition} userPosition={userPosition} points={points} legs={calculation.legs} polygon={mode!=="manual"} drawing={drawing} center={center} fit={fit} onAdd={p=>{if(points.length>=200){setMessage("Limite de 200 pontos por plano.");return;}if(validPoint(p))changePoints([...points,p]);}} onMove={(i,p)=>{if(validPoint(p))changePoints(points.map((v,j)=>i===j?p:v));}}/>
 <div className="map-instruction"><b>{mode==="manual"?"01 / TRACE O PERCURSO":"01 / CONTORNE A ÁREA"}</b><span>Importe uma área ou localize as coordenadas antes de desenhar. Clique para adicionar pontos; arraste para ajustar. Aproxime o mapa para conferir o terreno.</span></div>{calculation.error&&<p role="alert" className="flight-error">{calculation.error}</p>}
 <details className="point-table"><summary>Coordenadas do plano <span>{points.length} pontos</span></summary><div><table><thead><tr><th>Ponto</th><th>Latitude</th><th>Longitude</th><th/></tr></thead><tbody>{points.map((p,i)=><tr key={i}><td>{String(i+1).padStart(2,"0")}</td><td>{p[1].toFixed(6)}</td><td>{p[0].toFixed(6)}</td><td><button aria-label={`Remover ponto ${i+1}`} onClick={()=>changePoints(points.filter((_,j)=>i!==j))}>Remover</button></td></tr>)}</tbody></table></div></details><p className="mission-note">Estimativa sobre terreno plano. O tempo não inclui curvas, conexões entre faixas, decolagem, retorno ou reserva de bateria. A altura ainda não considera o relevo. O mapa inicia com uma visão do Brasil; localize ou importe sua área para planejar.</p></section>
 <aside className="mission-controls"><div className="mode-selector" role="group" aria-label="Modo de planejamento">{([['manual','Waypoints'],['grid','Grid'],['double','Double grid']] as [Mode,string][]).map(([value,label])=><button key={value} aria-pressed={mode===value} className={mode===value?"selected":""} onClick={()=>setMode(value)}>{label}</button>)}</div>
 <section className="control-section"><div className="section-heading"><span>01</span><h2>Missão & câmera</h2></div><label>Nome da missão<input maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Modelo do drone<select value={selectedDrone?drone:"custom"} onChange={e=>{const profile=droneProfiles.find(p=>p.name===e.target.value);setDrone(profile?.name||"");if(profile)applyCamera(profile.cameras[0]);else customCamera();}}><option value="custom">Personalizado / selecionar modelo</option>{droneProfiles.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label>
 {!selectedDrone&&<label>Nome do drone<input maxLength={100} value={drone} onChange={e=>setDrone(e.target.value)} placeholder="Informe o modelo"/></label>}
 <label>Câmera e modo de foto<select value={selectedCamera?.id||"custom"} onChange={e=>{const camera=selectedDrone?.cameras.find(c=>c.id===e.target.value);if(camera)applyCamera(camera);else customCamera();}}><option value="custom">Parâmetros personalizados</option>{selectedDrone?.cameras.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
 <details open className="camera-specs"><summary>Especificações e cobertura</summary>{selectedCamera?<><dl><div><dt>Sensor</dt><dd>{selectedCamera.sensor}</dd></div><div><dt>Focal equivalente</dt><dd>{selectedCamera.equivalentFocal} mm</dd></div><div><dt>Campo de visão</dt><dd>{number(selectedCamera.fov)}°</dd></div><div><dt>Foto</dt><dd>{settings.imageWidth} × {settings.imageHeight} px{selectedCamera.estimatedResolution?" · estimada":""}</dd></div></dl><p>GSD estimado pelo campo de visão diagonal, em terreno plano e câmera para baixo. {selectedCamera.estimatedResolution&&"Resolução reduzida estimada a partir do modo máximo; confira as dimensões da sua foto."}</p><p>{selectedCamera.minInterval===null?"O fabricante não lista disparo temporizado neste modo de resolução.":`Intervalo mínimo de foto temporizada: ${selectedCamera.minInterval} s.`} {selectedDrone?.note}</p></>:<><p>Preencha os dados da câmera. Dimensões físicas e focal real são diferentes da focal equivalente.</p><div className="camera-fields">{(settings.diagonalFov!==undefined?[["diagonalFov","FOV diagonal · °"],["imageWidth","Largura foto · px"],["imageHeight","Altura foto · px"]]:[['sensorWidth','Largura sensor · mm'],['sensorHeight','Altura sensor · mm'],['focal','Focal real · mm'],['imageWidth','Largura foto · px'],['imageHeight','Altura foto · px']] as [keyof Settings,string][]).map(([key,label])=><label key={key}>{label}<input type="number" min="0.01" step="any" value={Number.isFinite(settings[key as keyof Settings])?settings[key as keyof Settings]:""} onChange={e=>setField(key as keyof Settings,e.target.value)}/></label>)}</div></>}
 {calculation.gsd&&<dl><div><dt>GSD / nadir</dt><dd>{number(calculation.gsd.gsdX,2)} cm/px</dd></div><div><dt>Cobertura por foto</dt><dd>{number(calculation.gsd.footprintWidth)} × {number(calculation.gsd.footprintHeight)} m</dd></div></dl>}{selectedDrone&&<a href={selectedDrone.source} target="_blank" rel="noreferrer">Fonte do fabricante ↗</a>}</details></section>
 <section className="control-section"><div className="section-heading"><span>02</span><h2>Parâmetros do voo</h2></div>{sliderFields.map(([key,label,unit,min,max])=><label className="slider-control" key={key}><span>{label}<span><input aria-label={label} type="number" min={min} max={max} step="any" value={Number.isFinite(settings[key])?settings[key]:""} onChange={e=>setField(key,e.target.value)}/>{unit}</span></span><input aria-label={`${label} controle deslizante`} type="range" min={min} max={max} step={key==='speed'?0.1:1} value={Number.isFinite(settings[key])?settings[key]:min} onChange={e=>setField(key,e.target.value)}/></label>)}{calculation.gsd&&<div className="gsd-readout"><span>GSD previsto / nadir</span><b>{number(calculation.gsd.gsdX,2)} cm/px</b><small>Disparo a cada {number(calculation.gsd.interval,2)} s para a sobreposição informada</small></div>}{selectedCamera&&calculation.gsd&&selectedCamera.minInterval!==null&&calculation.gsd.interval<selectedCamera.minInterval&&<p role="status" className="camera-warning">O plano exige disparos mais rápidos que o intervalo listado para esta câmera. Reduza a velocidade ou escolha outro modo de foto.</p>}</section>
 <section className="control-section"><div className="section-heading"><span>03</span><h2>Arquivos do plano</h2></div><label className="import-button">Importar área ou plano<input aria-label="Importar KML, KMZ, GeoJSON ou plano Orion JSON" type="file" accept=".json,.geojson,.kml,.kmz" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value="";}}/></label><p className="muted">Área: KML, KMZ ou GeoJSON. Plano editável: JSON Orion.</p><div className="export-buttons"><button disabled={!calculation.legs.length||!!calculation.error} onClick={()=>{const bytes=previewKmz(name,calculation.legs,settings.height);download(new Uint8Array(bytes).buffer,"application/vnd.google-earth.kmz",`${filename}-visualizacao.kmz`);}}>KMZ · Google Earth ↗</button><button disabled={!calculation.legs.length||!!calculation.error} onClick={()=>download(missionCsv(calculation.legs,settings.height,settings.speed,settings.gimbal),"text/csv;charset=utf-8",`${filename}.csv`)}>CSV · coordenadas ↗</button><button disabled={!points.length||!!calculation.error} onClick={()=>download(JSON.stringify(plan,null,2),"application/json",`${filename}.json`)}>JSON · plano editável ↗</button></div><div className="compatibility"><b>DJI Fly / missão executável</b><p>A exportação para voo depende da validação do drone, controle e formato da missão. O KMZ acima serve para revisão no Google Earth.</p></div></section>
 </aside></div><footer className="flight-footer"><span>ORION MAPS · PLANEJAMENTO DE CAMPO</span><span>WGS84 / COORDENADAS GEOGRÁFICAS</span></footer></main></div>;
}

